### PR TITLE
Fix434 5 41

### LINKED ISSUE #434: 6.0.4-1 - The tabs are not closed
**Describe the bug**
When I try to close a TAB it doesn't close

**To Reproduce**
ASBRU version 6.0.4-1

1. I open a saved connection
2. I close the tab -> I confirm that I want to close it
3. The TAB does not close

**Expected behavior**
That the TAB would close

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Version 19.10

**Additional context**
Running CLI asbru-cm I find the following output when I try to close the TAB :

```
*** Vte::Terminal::feed_child: passed too many parameters (expected 2, got 3); ignoring excess at /opt/asbru/lib/PACUtils.pm line 3881.
*** unhandled exception in callback:
***   need an array ref to convert to GArray at /opt/asbru/lib/PACUtils.pm line 3881.
***  ignoring at /usr/share/perl5/Gtk3.pm line 572.
```

### PR DESCRIPTION
**Pull request by hanspr**
Fix #434 #435 #441 

Proposal to test capabilities instead of chasing version numbers.

We test what the current installed terminal library can or not do, set flags and then based on the flags apply the correct algorithms.

Have not tested the changes in PACUtils.pm with newer Vte version, only have 52

### CODE REVIEW

**Comment by gfrenoy** [comment]
Great idea !

It looks like we are showing more are more information at startup ... Can we just display the VTE version at startup and display capabilities only if a "verbose" mode is enabled ?

**Comment by hanspr** [comment]
>Can we just display the VTE version at startup and display capabilities only if a "verbose" mode is enabled

I will add the version in a minute

And do not see a verbose mode. And honestly when people send reports, the must common useful thing that we receive as support is that initial list of messages.

It also helps me when I'm testing new stuff, I usually run from the console.

When the application starts from the menu that stuff goes nowhere, so is not that it bugs anyone (or it does?). And when you run it manually, to report a bug, a want to have as much information as possible on that first interaction.

But if you still think that is to much, confirm and I will have to add a --verbose flag and  hide the loop information.

**Comment by gfrenoy** [comment]
Oh really, we don't have that --verbose flag yet ?  Well, maybe a good opportunity :)

In "normal" mode, I think it is "scary" to see a very long list of kabbalistic texts ; having a clear, concise list of very informative instructions will increase the trust.

If we have the VTE version number, we can deduct the capabilities so I would only show this by default.

**Comment by hanspr** [comment]
Ok

>If we have the VTE version number, we can deduct the capabilities so I would only show this by default.

This proves you wrong

```
} elsif (Vte::get_major_version() >= 1 or Vte::get_minor_version() == 52) {
        # Some distros have a special patched version of v0.52 that still requires 2 parameters; some others only one
        # Not nice but let's ignore the warning for that special case
        # See https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/1780501
        eval {
            local $SIG{__WARN__} = sub {};
            $vte->feed_child($str, $b);
            1;
        } or do {
            $vte->feed_child(\@arr);
        };
```

**Comment by gfrenoy** [comment]
> This proves you wrong

Eh eh, good point :-)

But in that very exceptional case, we can ask for an additional contribution of the one that is reporting the issue, don't you think ?

I mean, my reasoning is : let's make it short and informative for 99% of our cases and let's keep the "verbose" mode for the other cases.

Or said again differently: why would you bug 100 people with an information that is only useful for 1 of them...Let's ask to that single person to do an additional effort.

**Comment by hanspr** [comment]
Done

**Pull request merged**
