### PR TITLE
Fix530

### LINKED ISSUE #530: Fedora 31 - Transparancy doesn't work
Hi,

Terminal transparency doesn't work on Fedora 31, is there any way to make it work?

### PR DESCRIPTION
**Pull request by hanspr**
Fix #530 

Added setPaintable to tabbed window.

### CODE REVIEW

**Comment by hanspr** [comment]
Settings

imagen

imagen

imagen

imagen

**Comment by gfrenoy** [comment]
Made the changes in this feature branch:

- Add a new global setting "terminal support transparency" that defines if transparency is supported
- Default value of "terminal support transparency" is 1 if "terminal transparency" is greater that 0, otherwise 0
- If "terminal support transparency" is 1, window painting is set and transparency is possible for any other terminal
- If "terminal support transparency" is 0, transparency will not be possible for any of the terminals

Having this new option ensures that the "hack" for transparency does not impact performances or may cause side effects in the future.

Let me know if this looks OK to you and I'll merge this to loki.

**Comment by hanspr** [comment]
Looks fine, hope you can document it as well in the docs to round it up.

**Comment by hanspr** [comment]
I have found how to get the original theme background color but the process looks very inefficient to me.

```
# Get the bacground color, turn to string, split, remove, extra stuff.

my ($r,$g,$b,$a) = split /,/,$w->get_style_context()->get_background_color('normal')->to_string();
$r =~ s/\D//g;                                                                                    
$a =~ s/\D//g;                                                                                    
$c->set_source_rgba($r,$g,$b,$a);                                                                 

```

Have to find out how to assign the color object directly without having to pass as it as a string.

**Comment by hanspr** [comment]
This does not work for me,

imagen

It says that the method does not exists.

**Comment by hanspr** [comment]
Man, I just read in the manuals has been depreciated

**Comment by hanspr** [comment]
Ok, there are 2 ways to implement this.

1) You find the rgba colors once, and you will not be able to update if the user changes the theme.

```
sub _setWindowPaintable {
    my $win = shift;

    ($R,$G,$B,$A) = split /,/,$win->get_style_context()->get_background_color('normal')->to_string();
    $R =~ s/\D//g;
    $A =~ s/\D//g;
    $win->signal_connect("draw" => \&mydraw);
    my $screen = $win->get_screen();
    my $visual = $screen->get_rgba_visual();
    if (($visual) && ($screen->is_composited())) {
        $win->set_visual($visual);
    }
    $win->set_app_paintable(1);
}

sub mydraw {
    my ($w,$c) = @_;

    $c->set_source_rgba($R,$G,$B,$A);
    $c->set_operator('source');
    $c->paint();
    $c->set_operator('over');
    return 0;
}
```

2) You get the current color on every repaint

```
sub _setWindowPaintable {
    my $win = shift;

    $win->signal_connect("draw" => \&mydraw);
    my $screen = $win->get_screen();
    my $visual = $screen->get_rgba_visual();
    if (($visual) && ($screen->is_composited())) {
        $win->set_visual($visual);
    }
    $win->set_app_paintable(1);
}

sub mydraw {
    my ($w,$c) = @_;

    my ($R,$G,$B,$A) = split /,/,$w->get_style_context()->get_background_color('normal')->to_string();
    $R =~ s/\D//g;
    $A =~ s/\D//g;
    $c->set_source_rgba($R,$G,$B,$A);
    $c->set_operator('source');
    $c->paint();
    $c->set_operator('over');
    return 0;
}

```

So what would be your opinion on this

**Comment by hanspr** [comment]
Sadly, for some strange reason if does not work with the dark theme, it does not pull the correct backgorund color, so back to square 2, now. The solution is somewhere there.

**Comment by hanspr** [comment]
This last push is a walk around the issue, I know is an aberration, but I'm tired of fighting with gtk

Can't find how the get the current background color of a theme, window, nothing.

Even if I could, I was playing with the method set_source_rgba()

And I do not know if it is my computer, a perl gtk problem, or (most likely) I do not know how to use those objects. So I can only get these sets of colors to work :

+ 0,0,0,1
+ 255,255,255,1
+ 255,0,0,1
+ 0,255,0,1
+ 0,0,255,1

Any other combination turns into one of those above. So I can not get a simple grey color.

If you can find how to do it, then just fix it, If you can't and want to offer a walk around in the mean time, this is the only one I can offer.

The walk around is to set white or black as the background depending on the selected theme, and squash all widdgets tight together to minimize the effect.

**Comment by hanspr** [comment]
Update,

I have learned how to set the background color, the rgb values have to be all decimal values. So obvious.

If I can find the way to get the default background color it will be done.

**Comment by hanspr** [comment]
Finnally, found the background color, it was as I did it before, but the numbers had to be devided by 255

Now it works and changes the color dependind on the current theme and does not requiere to restart because is in the mydraw() subroutine.

light theme

imagen

switched to dark, and it adjusts

imagen

**Comment by hanspr** [comment]
Final version now this is how it should be.

**Pull request merged**
