### PR TITLE
Docs 1

### PR DESCRIPTION
**Pull request by hanspr**
Lets see how it works the first attempt to document.

### CODE REVIEW

**Comment by gfrenoy** [comment]
Be careful ; you're merging the loki branch to master ...

**Comment by hanspr** [comment]
Sorry, so I have to work from master or merge to loki?

**Comment by gfrenoy** [comment]
> I have to work from master or merge to loki?

Well, both are fine but the "pace" is not the same:

1) If you work from master --> documentation will be published "nearly" immediately
2) If you work from loki -> documentation will be published when loki will be merged to master (it will eventually happen but who knows when... ;-p)

**Comment by KlaasT** [comment]
Sorry I have to correct there a Bit. Please feel free to commit into loki. At at the moment I'm keeping an eye on the docs and will merge the docs into master.

**Comment by gfrenoy** [comment]
> Sorry I have to correct there a Bit. 

Thanks !!  I updated the answer :sunglasses:

**Pull request closed without merging**
