### PR TITLE
added feature #295 copy password, passphrase from terminal, connections

### PR DESCRIPTION
**Pull request by hanspr**
Added option to right clic menus on : terminal and connections.

Connections

imagen

Terminal

imagen

### CODE REVIEW

**Comment by B1tl0rd** [comment]
would have to identify it with another name. so that it does not conflict with the option that comes by default. which is to paste the password of the current session
image

**Comment by hanspr** [comment]
@B1tl0rd , are you sure you are testing this branch? 

My images above and the one I just took, show like Copy Connection Password, not paste.

imagen

Though in my version checks for password or passphrase because you use one or the other.

But the original paste was just checking for passwords, so now it checks for passphrase too. But in any case, should show one row for copy and another for paste, if it shows only paste I think you are not testing this branch.

**Comment by B1tl0rd** [comment]
No, I have not tried this change yet, I had only detailed this image.

**Comment by gfrenoy** [comment]
Hans, don't we want to "factorize" the code a bit ?

And do we really need it in the terminal ?  I would assume that the initial request was only to have it in the connection list ...

**Comment by hanspr** [comment]
> don't we want to "factorize" the code a bit ?

I don't know if I understand correctly this expression, if it is related to the fact that I'm using one test to copy pass or passphrase. I did it because I think you can not have both at the same time, the terminal edition activates one or the other.

imagen

Of course, if the users start using the terminal configuration as a password manager then we would need to separate. But initially it makes no sense to me to have both and use Asbru as a Password manager. But I understand the convenience to copy directly from within the application.

If this is not what you meant, then please explain it to me.

> Available in terminal

Reduces a step having to go to the list, but it can be removed, I do not mind. Is just an extra convenience. But if you think is unsafe in case of an unattended computer, then we can remove it, or we could consult with the user that made the request.

**Comment by gfrenoy** [comment]
>> don't we want to "factorize" the code a bit ?
> I don't know if I understand correctly this expression

Sorry about the [algebra jargon](https://en.wikipedia.org/wiki/Factorization) ; I meant that I see twice the same piece of code:
image

I was wondering if we can make one single function out of this ?

I know this has not been done a lot so far in the code we definitely need, if possible, to avoid copy/paste of code snippets.

> Available in terminal

If I get the use case correctly, you are in "terminal B" and wanting to have the password of "terminal A" so you'll need to get that password from another connection, anyway.

Having the option to paste the password of the *current* connection is likely another use case.

**Comment by hanspr** [comment]
I will create the function to do so in a minute

Original text

>Suppose that you have an SSH session established to host A.
>Then you need to SCP a file from host B into host A and that authentication with password is required.
>It would be nice to have an option in the context menu of the connection B to easily copy its >password into the clipboard and then simply paste it while doing the SCP authentication on host A.

This request is very complicated to achieve, I understand it as:

* I already have terminal A open.
* Want to SCP into A from B to put a file or SCP from B to A to pull a file.
* Have a context menu in Terminal B (this is a terminal) to copy password from A. This is too cumbersome. Using B to access A. Way to many jumps inside the application to accomplish that and locate the one you want to pull from.

But to me there are 2 short paths to get the password you want.

From an existing opened terminal, or the list.

Use case, example that happens to me very often:

* I open an ssh connection with asbru
* Go to my file manager (outside asbru) and type my scp://.... to open a remote folder on my desktop file manger.

imagen

*  The terminal is already available and accessible to reach for the password, and pass it to the file manager

**Comment by hanspr** [comment]
Code has been "factorized" :factory:

**Comment by B1tl0rd** [comment]
I think he means, with scp it's by command line from the terminal example.
scp  file.tar.gz user@remotehost:/home/user/
then be able to paste the password of the remote host

**Comment by hanspr** [comment]
@B1tl0rd , yep you right.

My image was wrong. I actually do : sftp://server/... and have to paste the passphrase from my already opened terminal.

Still think the convenience to have access to the password from the terminal or list, is for a wider use cases besides scp: rsync, sftp, to create a new certificate, to open a certificate locally, etc.

Of course I use KeePassXC, but the convenience of having another method is not bad after all.

Even if we connect Asbru to KeePassXC, we could pull it from there too. To avoid having to jump out of the application.

**Comment by gfrenoy** [comment]
Thanks for the great work Hans :)

Just a quick note: Klaas has merged the gtk3 branch to master so, unless you want to start a "huge" change, you should now branch from the master to create your new PR.

**Comment by hanspr** [comment]
@gfrenoy 

Got it. Good to know you have decided the new version was ready.

**Pull request merged**
