### PR TITLE
[Doc] Adding Note for Fedora install 

### LINKED ISSUE #1096: fedora 40 can't find pacakage.
**Describe the bug**
Can not install asbru-cm... 
No match for argument: asbru-cm
Error: Unable to find a match: asbru-cm

I checked the yum.d.config files and they look ok

**Environment (please complete the following information):**
 - OS: Fedora 40
 - Ásbrú Version any, tried all.

```
[~]$  curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/loki/cfg/setup/bash.rpm.sh' | sudo -E bash
Executing the  setup script for the 'asbru-cm/loki' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'rpm' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=fedora  version=40  codename=KDE  arch=x86_64
 >>>>:
   OK: Importing 'asbru-cm/loki' repository GPG keys into rpm ...
   OK: Checking for available package manager (DNF/Microdnf/YUM/Zypper) ...
 ^^^^: ... Detected package manager as 'dnf'
   OK: Checking for dnf dependency 'dnf-plugins-core' ...
   OK: Checking if upstream install config is OK ...
   OK: Fetching 'asbru-cm/loki' repository configuration ...
   OK: Installing 'asbru-cm/loki' repository via dnf ...
  RUN: Updating the dnf cache to fetch the new repository metadata ...Importing GPG key 0x84******:
 Userid     : "Cloudsmith Package (asbru-cm/loki) <support@cloudsmith.io>"
 Fingerprint: ****
 From       : https://dl.cloudsmith.io/public/asbru-cm/loki/gpg.1C9DA11D84B20237.key
Importing GPG key 0x84B20237:
 Userid     : "Cloudsmith Package (asbru-cm/loki) <support@cloudsmith.io>"
 Fingerprint: ********
 From       : https://dl.cloudsmith.io/public/asbru-cm/loki/gpg.1C9DA11D84B20237.key
Importing GPG key 0x84B20237:
 Userid     : "Cloudsmith Package (asbru-cm/loki) <support@cloudsmith.io>"
 Fingerprint: *****
 From       : https://dl.cloudsmith.io/public/asbru-cm/loki/gpg.1C9DA11D84B20237.key
   OK: Updating the dnf cache to fetch the new repository metadata ...
   OK: The repository has been installed successfully - You're ready to rock!
[~]$ sudo dnf install asbru-cm
Last metadata expiration check: 0:00:03 ago on Sun 23 Jun 2024 01:30:48 PM BST.
No match for argument: asbru-cm
Error: Unable to find a match: asbru-cm
```

### PR DESCRIPTION
**Pull request by Yarboa**
Docs workaround for Fedora > 37

resolve #1096

### CODE REVIEW

**Comment by Yarboa** [comment]
@gfrenoy can you take a look please

**Comment by gfrenoy** [comment]
Thanks a lot for your help @Yarboa :-)

If we do document this in the README, we should do it for all distributions.

I do think it would be more useful to have a change in the wiki pages related to installation, see "Installation" on https://github.com/asbru-cm/asbru-cm/wiki ; and in the README, we could have a note that redirect to the wiki pages.

**Comment by Yarboa** [comment]
> Thanks a lot for your help @Yarboa :-)
> 
YW
> If we do document this in the README, we should do it for all distributions.
> 
Ack
> I do think it would be more useful to have a change in the wiki pages related to installation, see "Installation" on https://github.com/asbru-cm/asbru-cm/wiki ; and in the README, we could have a note that redirect to the wiki pages.

Sure, do you refer update this page instead?
https://github.com/asbru-cm/asbru-cm/wiki/installation-on-fedora

**Comment by gfrenoy** [comment]
> do you refer update this page instead?
> https://github.com/asbru-cm/asbru-cm/wiki/installation-on-fedora

For Fedora, yes.

**Comment by gfrenoy** [comment]
Pacakges for F40 has been released + the documentation review should be more complete; let's close this for now.

**Pull request closed without merging**
