### PR TITLE
Fix323 FOR TESTING

### PR DESCRIPTION
**Pull request by hanspr**
This is the first version to remove Net::Proxy from #323, and address #280, #67, #218 

This version has a print to show the connection string used to connect to test in case of errors, we need to remove after we have confirmation that the interface works properly.

__General Changes to the interface__

* General Settings
    * Renamed to networking
    * Changed logic to options
    * Added Jump Server global options
    * Renamed labels

imagen

* Terminal Connection Settings
    * Changed to networking
    * Added Jump Server
    * Renamed labels

imagen

__Currently Tested, case #280__

* Configure to first connection gateway machine, add Dynamic port

imagen

* Configure access to second machine connection, add connection information

imagen

* Setup networking matching Dynamic IP/PORT, setup on first terminal connection

imagen

__Test results__

Connection to intermediate machine, correct
imagen

Connection to machine in local network correct

imagen

---

__Case #67__

After a lot of reading, got to the conclusion that this method only works with passwordless connections. So to me the easiest setup would be to create entries in .ssh/config, similar to this

imagen

imagen

2 Entries should be created one for the Jump Server and the second for the target machine

And then configure Asbru like this

* Connection with to second machine used in .ssh/config

imagen

* Configure networking, with name of JumpSever used in .ssh/config

imagen

__Test results__

imagen

---

Please test, and confirm if it works for you.

### CODE REVIEW

**Comment by gfrenoy** [comment]
Waw, great !  Our next milestone (https://github.com/asbru-cm/asbru-cm/milestone/2) is maybe closer than I initially thought :)  Thanks again for your great contributions :)

We should merge this the "[loki](https://github.com/asbru-cm/asbru-cm/tree/loki)" (unstable) branch so that we can keep the "master" ready for hot fixes.

Do you see how to do this and will you have time ?  Otherwise, I can have a look on my side.

One remark : the merge of the glade file will likely be tricky but you can just revert my recent changes, I will re-apply them afterwards.

**Comment by hanspr** [comment]
I do not know how to change the merge to "loki", except to remove this PR and create it again, is there a simpler way? or should I remove it and send it again?

**Comment by hanspr** [comment]
Found it

**Comment by gfrenoy** [comment]
Ok, I merged your version and then re-apply my changes.

So we should have the "latest and greatest" version on loki now...

Let make some tests !

**Comment by hanspr** [comment]
Ok, I think I have it updated, I'll wait for your feed back

**Comment by gfrenoy** [comment]
Yes, you'll need to get the latest glade file.  It's actually a nightmare to follow up the changes ; it looks like glade is constantly changing things that I did not touch.

Anyay.

I started to look at the "jump" option but got confused by the "SSH config" ; shouldn't we just mimic what was initially suggested (#70).  I would assume that such a "jump host" would work with a SSH key ...

**Comment by hanspr** [comment]
I think you refer to a different issue than #70 , think you refer to #67 

Well I wanted to be able to tell the difference between an .ssh/config entry and a user@server:port setup

Is different, you may rename it or change into 2 different lines, if you think it makes it clearer, but the concepts are different

This is related to this my reference

>After a lot of reading, got to the conclusion that this method only works with passwordless connections. So to me the easiest setup would be to create entries in .ssh/config, similar to this

SSH Config, tells me that I should create a command line like : ssh -J machine1 machine2

The other entries tell me to build : ssh -J user@machine1:port user@machine2:port

**Comment by hanspr** [comment]
> would assume that such a "jump host" would work with a SSH key ...

Yes but again is not possible to pass that parameter with an -J option, so the option in #67, is useless.

You have to configure .ssh/config or create a rsa key, but can not build a command line to use it.

To build your rsa you should follow a similar approach as this: https://www.tecmint.com/ssh-passwordless-login-using-ssh-keygen-in-5-easy-steps/

But to me is a lot simpler to create .ssh/config entries, is by far more flexible.

**Comment by hanspr** [comment]
For example, move the settings like this

imagen

So you can tell if you want to use an SSH config entry or a user@machine:port configuration.

This are some of the references I used to understand the -J option

https://www.tecmint.com/access-linux-server-using-a-jump-host/

Do you wan't me to move the glade file again? to make it look like the image?

**Comment by gfrenoy** [comment]
I'm just thinking loud:

- Users of a GUI as Ásbrú probably don't want to know something about ssh_config ; they do expect the UI will help them making this as easy and straightforward as possible
- Can't we have only one "Host" field ?  If that host is defined in ssh_config, ssh will use it "automagically"
- In the tooltip, we can explain it can also be an IP address or a SSH config entry
- Port will need to remain empty (that should be the default, I would guess, not 8080)
- To use a SSH key, I indeed think we need to use the "legacy" ProxyCommand version (see all examples [there](https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts#Passing_Through_One_or_More_Gateways_Using_ProxyJump))

**Comment by hanspr** [comment]
Do you have time to chat, where, the link https://webchat.st-city.net/#asbru-cm is always down now

**Comment by hanspr** [comment]
Think I have a very good solution, give me an hour

**Comment by gfrenoy** [comment]
Yes but indeed, the St-City webchat seems to be down today ; I'll ask around if we can fix this.

In the meantime, you'll need to find another IRC client.  Just tried this one: https://kiwiirc.com/nextclient/ ; looks to work ... Server is irc.st-city.net ; channel #asbru-cm

**Pull request merged**
