### PR TITLE
Facelift 1

### PR DESCRIPTION
**Pull request by hanspr**
@gfrenoy 

This PR is not a finished work, is more a start on the ideas I've been running in my head.

The icons are mainly there to enable the code, you may change them all or keep any one that could be worth to save.

In general, this is the main look for the Traditional mode.

imagen

### Allow to select Unprotected and Protected nodes colouring

imagen

The thing is that I prefer to __stand out__ what is dangerous, than what is not.

With the current model, all unprotected nodes are black, and protected nodes are coloured. If you want to use the reverse logic, all protected nodes black and unprotected red, you can not do that.

With this change you can setup the views at the top, where protected nodes look normal and unprotected nodes stand out in a red background

## Improved visual information to the user

Some of the things that I think should be improved is to visualy help the user know where is interacting.

So I introduced some basic classes in asbru.css

__Highlight buttons__

imagen

__Highlight and compact some buttons__

imagen

__Highlight focused text entries__

imagen

imagen

__Add a bit of spacing between buttons__

imagen

imagen

## Make compact mode, more compact

Buttons, are reduced to their minimal size, and window decoration has been removed.

imagen

### CODE REVIEW

**Comment by gfrenoy** [comment]
Very colorful :)  Looks good.  Thanks !!!

To polish even a bit more, here are a few suggestions / questions / ideas:

- [ ] Have bit more space (padding) between the folder icon and text
- [ ] The SSH icon is not as "square" as the others (there is empty space on the left/right) ; would look nicer if is match the occupation of the other icons
- [ ] When you save the preferences (or connection settings), the button "Close without saving" is briefly highlighted
- [ ] Remove all unused .png files
- [ ] Remove all useless "frames" in preferences
- [ ] Have the same margins in all preferences panels
- [ ] Have the same "yellow highlight" when focus is set on a combobox, checkbox (now only text box)
- [ ] For some reason, icons are not shown in the main bar button (near "Wake On Lan" as an example) ; is there a way to force this ?

And maybe ideas for the longer run:

- [ ] Store all svg in a separated folder so that we have "themes"
- [ ] Allow user to override the group / connection icons

**Comment by hanspr** [comment]
I'm reworking the icons now, less bright, size.

Thought about the themes but it requires quit a deeper design on the desisions naming classes, once we introduce a name and attach will be hard to undo. So I would like to leave it for another version.

Will check the rest, I hope I can send an retouched version in a few minutes, and more icons.

**Comment by hanspr** [comment]
Have bit more space (padding) between the folder icon and text (__DONE__)

The SSH icon is not as "square" as the others (there is empty space on the left/right) ; would look nicer if is match the occupation of the other icons (__CHECK__)

When you save the preferences (or connection settings), the button "Close without saving" is briefly highlighted (__DON'T SEE IT__)

Have the same "yellow highlight" when focus is set on a combobox, checkbox (now only text box) (__CSS does not work will with this kind of widgets you may try, don't think is necessary this are one time interaction elements that clearly show their settings after interacting with them. Is not like you stay in them for a long time like text boxes, move your eyes somewhere else and then come back to tr to find where you were__)

For some reason, icons are not shown in the main bar button (near "Wake On Lan" as an example) ; is there a way to force this ? (__DON'T SEE IT, send image to understand__)

Other improvements:

* Homologate icons canvas and sizes
* More solid icons and less shiny

imagen

**Comment by gfrenoy** [comment]
> For some reason, icons are not shown in the main bar button (near "Wake On Lan" as an example)

image

I would assume it's related to a Gnome / Theme setting...?

> When you save the preferences (or connection settings), the button "Close without saving" is briefly highlighted

output

Very brief but very confusing when you quickly click and you are not sure anymore of what you exactly did :-/

**Comment by hanspr** [comment]
The first image is strange because it does not happen to me. I think you are on Ubuntu (would have to set up a virtual machine) This happens with this PR? or in general?

The second one is a technique that I have seen many times being used in several windows, like clusters, etc. When you click on "Save  and close" what it does is : save the configuration and then trigger a button click on the "close button" to close the window.

**Comment by gfrenoy** [comment]
>  This happens with this PR? or in general?

Not specific to this PR at all.  It has been like this for a long time.

And is certainly specific to the Ubuntu theme.  My best guess today is that the theme does not define the stock icon or something like.  Don't worry, not a big deal.

>  When you click on "Save and close" what it does is : save the configuration and then trigger a button click on the "close button" to close the window.

Oh!!  Of course, I understand !  I will fix this ; it bugs me for years :)  Thanks for tip !

**Comment by hanspr** [comment]
> For some reason, icons are not shown in the main bar button (near "Wake On Lan" as an example)

I send a new PR adding a wake on lan icon.

I can see the new icon for connection list shown in your image, so maybe the missing icons are missing in your resources directory or the svg and png icons can not be mixed? Lets, see if the new wake on lan icon shows on your button to have more information.

**Comment by hanspr** [comment]
> Oh!! Of course, I understand ! I will fix this ; it bugs me for years :) Thanks for tip !

Just check why it was done like that, maybe some code has to run on a close button click and maybe that is why was designed like that.

**Comment by gfrenoy** [comment]
> For some reason, icons are not shown in the main bar button (near "Wake On Lan" as an example)

Read paragraph "Icons or text ?" here : https://wiki.gnome.org/HowDoI/Buttons
And questions like these : https://stackoverflow.com/questions/8989833/gtk-menu-with-icons

So it's "by design"... Mmm.

**Comment by gfrenoy** [comment]
> Just check why it was done like that,

Yes, I guess this idea was to "factorize" but we should have a common function for both ; not clicking on the button that has some side effects.  That's an easy fix !

**Comment by hanspr** [comment]
> Read paragraph "Icons or text ?"

If we want to homologate looks across distributions, maybe we could choose for text only buttons for the ones that could be not very obvious what is the action on that button (Wake on Lan, Scripts, Clusters, etc).

Or go for  just icons and with the tooltip inform the action. In the compact mode I have only icons, and tooltips.

**Comment by hanspr** [comment]
Added background colour on hover to radio and checkboxes, looks a bit odd in some cases, perhaps we will need to remove all the expands to the radio and checkboxes.

imagen

imagen

**Comment by gfrenoy** [comment]
It looks good :)

But it makes things different than for the text inputs ...

Shouldn't we try to have the same behavior for all widgets ?  One color for hover (light gray) and one color for focus (orange) ?

**Comment by hanspr** [comment]
Buttons, radio and checkboxes highlight white and white on hover.

Textboxes show yellow background on focus.

**Comment by hanspr** [comment]
Hover does not work over entry fields, is a bug wont fix until gtk4

**Comment by hanspr** [comment]
Would you prefer black and white icons for the buttons?

imagen

I began with colours because the original button icons had colours, but could be all black and white.

**Comment by hanspr** [comment]
From your list

* When you save the preferences (or connection settings), the button "Close without saving" is briefly highlighted __(DONE)__
* Remove all unused .png file __(Leave the removing to you, you decide)__
* Remove all useless "frames" in preferences __(This I think it could be more difficult than it sounds, I do not know if we should do it on this round or on a second one)__
* Have the same margins in all preferences panels __(Don't understand this one)__
* Have the same "yellow highlight" when focus is set on a combobox, checkbox __(DONE)__
* For some reason, icons are not shown in the main bar button (near "Wake On Lan" as an example) ; is there a way to force this ? __(can be solved?)__

Well check what you really would like to complete for 6.1.

With respect to icons, that is all the design talent that I have, if does not suffice we may need to find graphics designer that would like to jump in.

**Comment by gfrenoy** [comment]
Thanks again, it looks really great !

> Remove all unused .png file (Leave the removing to you, you decide)

If we don't use them, no reason to keep them in the repository.

> Would you prefer black and white icons for the buttons?

Both look really great :smile: and I cannot decide ... :thinking: 

Actually, I would prefer I can choose to change every day :)

If we put all the SVG files in one directory and then give the name of the folder as a parameter in the configuration ... would that really be a big change ?

> Have the same margins in all preferences panels

Most of the panels do not have a margin at all:
image

For the new ```Network Settings```, I put a very large margin:
image

Not sure what is best (no margin, small margin or large margin) but I think we can easily agree that it should be consistant in all panels of the application...

> Well check what you really would like to complete for 6.1.

We are already far beyond you know :)

> With respect to icons, that is all the design talent that I have,

I wished I had your talent :)

> if does not suffice we may need to find graphics designer that would like to jump in.

Sure and if we have all SVG in one directory ; that'd probably easy the work to know what needs to be done.

**Comment by hanspr** [comment]
Added theme chooser at Preferences

Default black icons, and asbru-color

imagen


imagen

imagen

**Comment by gfrenoy** [comment]
Waaaoooww !  Brilliant :astonished: !!

I'll pick the "asbru-color" theme for today :-))))

Thank you so much.

**Comment by wcasanova** [comment]
Great job friend..

**Comment by hanspr** [comment]
>Well check what you really would like to complete for 6.1.
>>We are already far beyond you know :)

Well then we need another branch where I can begin joining this, fix50, fix65 because is getting to complicated for me to keep up all this stuff separated.

Or what would be the strategy?

**Comment by gfrenoy** [comment]
> Or what would be the strategy?

imho : 
1) let's focus on and finish what was in the 6.1 scope (basically find a way to have that SOCKS proxy working aka Net::Proxy replacement) and release it !
2) merge all pending PR to loki and select what we will put in 6.2

**Comment by KlaasT** [comment]
Just wait with merging further PRs into loki until Loki is merged into master. Will make things less complicated

**Comment by wcasanova** [comment]
A question when merged with the loki branch?

**Comment by gfrenoy** [comment]
Short answer : soon :)

Have to finalize a few things for 6.1 and then, those pending PRs will be merged to loki and we can start on 6.2.  Stay tuned :)

**Pull request merged**
