### PR TITLE
Treeview master

### LINKED ISSUE #306: (Snapshot Version 6) Folder appearance
**Is your feature request related to a problem? Please describe.**
I'm using new snapshot version 6, and having Groups and Subgroups is a bit messy now because all the folder listed are aligned, doesn't matter if is a main group or a subgroup, all are at the same level.

**Describe the solution you'd like**
Have a better hierarchy/alignment 

**Additional context**
See the attached picture:
Screenshot from 2019-12-12 16-55-54

Thanks

### PR DESCRIPTION
**Pull request by hanspr**
fix #306 

Ported to master to calm the clamour of the masses.

imagen

### CODE REVIEW

**Comment by hanspr** [comment]
@gfrenoy 

If you like, I can remove the new icons from this PR, leave only the fix for better indentation with the current icons, and we prepare a facelift for the new version working on a complete set of better icons.

**Comment by gfrenoy** [comment]
Indeed we can maybe use the ```png``` icons in 6.0 and leave the ```svg``` for 6.1.

But I'm more worried about the error messages I see on the console:

> GLib-GObject-CRITICAL **: g_object_thaw_notify: assertion 'G_IS_OBJECT (object)' failed at /usr/lib/x86_64-linux-gnu/perl5/5.26/Glib/Object/Introspection.pm line 67.
> GLib-CRITICAL **: g_hash_table_foreach: assertion 'version == hash_table->version' failed at /usr/lib/x86_64-linux-gnu/perl5/5.26/Glib/Object/Introspection.pm line 67.

**Comment by hanspr** [comment]
I'll try to see if I'm luckier this time to find them. And see how to stop glib from complaining if possible.

Have you seen a side effect or just the complains?

**Comment by gfrenoy** [comment]
Hans, I changed the way the column is built and all errors/warnings are gone.

The bottom line is that we cannot use ```Gtk3::CellRendererText``` but we have to create our own column renderer.

**Comment by hanspr** [comment]
Guauu, that is far to much gtk knowledge for my self, is fantastic that there are 2 heads to solve this kind of things.

**Comment by gfrenoy** [comment]
Yes, stronger together :)

**Pull request merged**
