### PR TITLE
Treeview 2

### LINKED ISSUE #306: (Snapshot Version 6) Folder appearance
**Is your feature request related to a problem? Please describe.**
I'm using new snapshot version 6, and having Groups and Subgroups is a bit messy now because all the folder listed are aligned, doesn't matter if is a main group or a subgroup, all are at the same level.

**Describe the solution you'd like**
Have a better hierarchy/alignment 

**Additional context**
See the attached picture:
Screenshot from 2019-12-12 16-55-54

Thanks

### PR DESCRIPTION
**Pull request by hanspr**
Fix #306 

imagen

### CODE REVIEW

**Comment by gfrenoy** [comment]
Oh *yes* the so much wanted change :))))  Thanks a lot Hans !

**Comment by gfrenoy** [comment]
I see the following error message with this PR:

> GLib-GObject-CRITICAL **: g_object_thaw_notify: assertion 'G_IS_OBJECT (object)' failed at /usr/lib/x86_64-linux-gnu/perl5/5.26/Glib/Object/Introspection.pm line 67.
> GLib-CRITICAL **: g_hash_table_foreach: assertion 'version == hash_table->version' failed at /usr/lib/x86_64-linux-gnu/perl5/5.26/Glib/Object/Introspection.pm line 67.

Don't see where it comes from...?

**Comment by hanspr** [comment]
I see them, have not been able to locate where are they created, and I do not see a consequence.

The only thing I know is that it complains because the columns that uses to join the information are hidden. But it does not do more than that.

I hide the one at the beginning, and I do not see does that you see. What action do you do to make the appear?

**Comment by gfrenoy** [comment]
I see them at startup.  No particular action.

**Pull request merged**
