### PR TITLE
Distribution: Raw AppImage builder using Docker

### LINKED ISSUE #804: Request for Appimage
Its quite a mission to bring asbru to work in opensuse-15.2

i would hope you would build an Appimage x-) 

thank you
-c-

### PR DESCRIPTION
**Pull request by henry701**
AppImage builder from scratch using Docker.

Closes #804.

PR here just for tracking, so far. It's still not working because Asbrú will need some code changes in order to invoke external executables without the environment variable mangling (that was done in order to run the AppImage with the correct relative paths of the embedded libs). More about the progress in the comments below.

To build the AppImage, you will need Docker installed and accessible from your POSIX shell. Then, just `cd` to the root directory of the project, and run: `./dist/appimage-raw/make_appimage.sh`. It will be available on `./dist/appimage-raw/build`.

### CODE REVIEW

**Comment by gfrenoy** [comment]
Thanks a lot Henrique !

I gave it a try and was able to build the AppImage but when executing it, I have the following message:

`execv error: Permission denied`

Is this what you mean with "invoke external executables without the environment variable mangling" or did I do something wrong ?

**Comment by henry701** [comment]
I'm usually having no such file or directory instead of permission denied, strange...

Anyways, this PR will take some more time to be ready, because of a lot of complexity:

- Asbru uses VTE to invoke itself and there's some issues arising with that due to the customized env vars.
- Every time we invoke a command which executable lies outside of the AppImage the original env vars have to be set.
- [I'm currently working on this] Local Shell is not working due to the X11 Perl module for some reason not detecting that it's running inside X11, in asbru_conn's window resizing code.
- There's some places (local shell directory configuration, so far) where we change the current working directory, but this will have to be changed for some other alternate method because changing cwd breaks AppImages
  - Changing CWD breaks AppImages because the ELF header of all executables are patched to use relative directories so that they invoke the embedded Shared Objects, not the system ones

So there's a LOT of stuff to iron out and make flexible, and there's a lot of code that's going to have to be changed to match.

Then after I'm done there will be a lot of testing both inside and outside AppImage to ensure the changed pieces are working fine.

About the permission denied problem, something somewhere is probably not marked as executable, I'm using WSL so maybe that has something to do with it, probably Windows "forces" execution even without the executable flag...

**Comment by henry701** [comment]
The X11 problem didn't occur today even though I changed nothing locally, very strange. At least now the shell finally opens :)

Just need to iron out this, current commit ignores the configuration option:

> - There's some places (local shell directory configuration, so far) where we change the current working directory, but this will have to be changed for some other alternate method because changing cwd breaks AppImages
>    - Changing CWD breaks AppImages because the ELF header of all executables are patched to use relative directories so that they invoke the embedded Shared Objects, not the system ones

And then more extensive testing, of course.

Also, sorry for not even saying on the PR how to build the docker image. I will edit it with the information.

**Comment by henry701** [comment]
Does the AppImage work for you after these last changes?

**Comment by gfrenoy** [comment]
> Does the AppImage work for you after these last changes?

No joy :(  Here is what I see if I run it on the same machine:

```
$ dist/appimage-raw/build/Asbru-CM.AppImage 
Gtk-Message: 10:15:04.368: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
syntax error at /tmp/.mount_Asbru-HlZ4og/opt/asbru-cm/lib/PACUtils.pm line 343, near "return"
syntax error at /tmp/.mount_Asbru-HlZ4og/opt/asbru-cm/lib/PACUtils.pm line 368, near "return"
BEGIN not safe after errors--compilation aborted at /tmp/.mount_Asbru-HlZ4og/opt/asbru-cm/lib/PACUtils.pm line 3812.
Compilation failed in require at /tmp/.mount_Asbru-HlZ4og/opt/asbru-cm/lib/PACMain.pm line 57.
BEGIN failed--compilation aborted at /tmp/.mount_Asbru-HlZ4og/opt/asbru-cm/lib/PACMain.pm line 57.
Compilation failed in require at /tmp/.mount_Asbru-HlZ4og/opt/asbru-cm/asbru-cm line 96.
BEGIN failed--compilation aborted at /tmp/.mount_Asbru-HlZ4og/opt/asbru-cm/asbru-cm line 96.
```

It looks like we are not using the right version of perl or using a "strict" mode or something ; I'm lost at this stage...

**Comment by henry701** [comment]
I actually forgot a `;` after logging some extra things and didn't run Asbrú before committing 🤦‍♂️ will fix this later

**Comment by gfrenoy** [comment]
> I actually forgot a `;` after logging some extra things and didn't run Asbrú before committing man_facepalming will fix this later

Oh yes, of course ... I see ; did not realize you made that many changes and that it was actually a "real" error ;)

So, I did fix it locally, tried again and ... it works !  That looks like a great news :)  I'll play around and we'll also need to see how we can automate this build in our Travis script.

Thanks a lot.

**Comment by henry701** [comment]
Both shell directory setting and use login shell settings work properly now. Still need to test more and check for strings used on anything that spawns a subprocess so that every one of those is checked for env variable prefixing, depending on what it does and what it invokes.

**Comment by henry701** [comment]
Seems stable and complete now. Missing docs for now

**Comment by henry701** [comment]
Docs done 👀

**Comment by gfrenoy** [comment]
Hi Henrique,

Thanks again for the terrific work to get this working !  I made a test with the latest loki release and was able to create an AppImage with the latest loki code.

It's working fine for me.  The only little glitch I see is the following message for every terminal you want to start:

```
Gtk-Message: 17:35:50.555: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
```

Any idea why I see this ?  Can we do something about it ?

I now need to see how we can build this automatically when we start our automated build.

**Comment by henry701** [comment]
I couldn't reproduce that here, it seems some GTK module outside the AppImage is being picked up.

From searching around about GTK module loading I saw some documentation about `GTK_IM_MODULE` and `GTK_IM_MODULE_FILE` environment variables, I'll adjust the _AppRun_ script to override them as well and see.

**Comment by henry701** [comment]
Try now on the branch, that `atk-bridge` module was on the `gtk-2.0` folder, so I pointed `GTK_PATH` to the `gtk-3.0` folder instead (and that's what Asbrú uses, so whoops).

**Comment by gfrenoy** [comment]
Henrique, still searching for a way to publish the AppImage from our automated build...

In the meantime, I created an entry on AppImageHub and uploaded manually:
   https://www.appimagehub.com/p/1796061

**Comment by henry701** [comment]
> Henrique, still searching for a way to publish the AppImage from our automated build...
> 
> In the meantime, I created an entry on AppImageHub and uploaded manually: https://www.appimagehub.com/p/1796061

Is using a separate build orchestration an option, or does it need to be on the same Travis CI? I can try to integrate with Travis CI or GitHub Actions and post the resulting code, if it would help :)

> Hi Henrique,
> 
> Thanks again for the terrific work to get this working ! I made a test with the latest loki release and was able to create an AppImage with the latest loki code.
> 
> It's working fine for me. The only little glitch I see is the following message for every terminal you want to start:
> 
> ```
> Gtk-Message: 17:35:50.555: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
> ```
> 
> Any idea why I see this ? Can we do something about it ?
> 
> I now need to see how we can build this automatically when we start our automated build.

Could you cherry-pick https://github.com/henry701/asbru-cm/commit/b95b324c11dcdcc017f507f82bf96f3d37e643be and try again? It probably solves the issue you described here.

**Comment by gfrenoy** [comment]
> Is using a separate build orchestration an option,

Yes, certainly.

> I can try to integrate with Travis CI or GitHub Actions and post the resulting code, if it would help :)

Well, adding this to Travis CI is fairly trivial *if* I would have a way to upload the build to AppImageHub (or anything else...).
I did not really find an API or a way to automate this :(

> Could you cherry-pick henry701@b95b324 and try again? 

Sure, will do.

Thanks again for this great feature !

**Comment by gfrenoy** [comment]
> Could you cherry-pick https://github.com/henry701/asbru-cm/commit/b95b324 and try again?

It works like a charm :)  Thanks a lot !

I uploaded "apha-2" on https://www.appimagehub.com/p/1796061

**Pull request merged**
