### PR TITLE
fixed regression tabbed terminals

### PR DESCRIPTION
**Pull request by hanspr**
Fix regression tabbed terminals not showing

### CODE REVIEW

**Comment by gfrenoy** [comment]
Reverting this will break #327 !

We should understand why you have that regression and find the right way to fix it for both cases.

Can you elaborate the case where SSH terminal does not work for you ?

**Comment by gfrenoy** [comment]
Ok I understand the problem ... You are using terminals outside the main window !  Let me find the right "show_all" ; we should not do that for all terminals ...

**Comment by hanspr** [comment]
Yes, so maybe with an if to test for that should make it work

**Comment by hanspr** [comment]
I'll wait for you because I'm about to add another PR

**Comment by gfrenoy** [comment]
Does "show()" instead of "show_all()" works for you ?

(it looks to fix both issues here...)

**Comment by gfrenoy** [comment]
@hanspr Ok just pushed https://github.com/asbru-cm/asbru-cm/commit/31d4c55b281efa196e25187a2da7730232e8df8c ; looks to work fine for me, let me know if you should still encounter some issues with terminals outside the main window.

**Comment by hanspr** [comment]
Yes it works, thanks

**Pull request merged**
