### PR TITLE
fix: delete script was not working

### PR DESCRIPTION
**Pull request by jojaquix**
A little script deletion fix.
================
Problem: The selected(s) scripts deletion was not working.

Before the change:
----------------------

image
and of course the scripts was not deleted

After the change
-------------------
No error raised and selected script deleted

### CODE REVIEW

**Comment by jojaquix** [comment]
@gfrenoy Do You think this could be merged ? Thanks.

**Comment by jojaquix** [comment]
Ohh great, well I was not able to find perl docs for GTK3 TreeView mode but [here ](https://gtk2-perl.sourceforge.net/doc/pod/Gtk2/TreeModel.html#_tree_model_get_valu) I found the get_value method takes as second parameter a list of indexes and that worked in my tests with current GTK library used by asbru-cm

**Comment by gfrenoy** [comment]
Can you give it a try with "0" if it still works ?

See https://docs.gtk.org/gtk3/vfunc.TreeModel.get_value.html, it looks to expect a "gint".  All the other calls in the same code are also only using an int so let's try to be consistent.

Thanks again for your help !

**Comment by jojaquix** [comment]
I have chaged to use only one gint @gfrenoy and it worked also.

**Pull request merged**
