### PR TITLE
update vte_feed_child detection

### PR DESCRIPTION
**Pull request by syco**
Signed-off-by: Syco <alberto.rinaudo+dino@gmail.com>

### CODE REVIEW

**Comment by gfrenoy** [comment]
Thanks!

For the other distros, don't we need to keep the `1;` so the `eval` succeeds ?

**Comment by syco** [comment]
The 1 doesn't make any difference in my tests, here's how I'm doing it:
```perl
use strict;
use warnings;
use Gtk3 -init;
use Glib::Object::Introspection;

Glib::Object::Introspection->setup(basename => 'Vte', version => '2.91', package => 'Vte');

my $terminal = Vte::Terminal->new();

my $str = "# do nothing";
use bytes;
my $b = length($str);
my @arr = unpack ('C*', $str);

eval {
  local $SIG{__WARN__} = sub { die @_ };
  print("Test 2 args: ");
  $terminal->feed_child($str, $b);
  print("OK 2\n");
} or do {
  print("ERROR, should be 1\n");
};

eval {
  local $SIG{__WARN__} = sub { die @_ };
  print("Test 1 args: ");
  $terminal->feed_child(\@arr);
  print("OK 1\n");
} or do {
  print("ERROR, should be 2\n");
};

exit(0);
```
```bash
$ perl terminal.pl 2>/dev/null
Test 2 args: ERROR, should be 1
Test 1 args: OK 1
```

**Comment by gfrenoy** [comment]
I would guess the `print` operation is returning something equivalent to 1 so that it works.  Can you try without anything after `feed_child` ?

As a matter of fact, this is what we are doing in `_setVteCapabilities`:

 ```perl
    $$self{_Vte}{vte_feed_child} = 0;
    eval {
        $vte->feed_child('abc', 3);
        1;
    } or do {
        $$self{_Vte}{vte_feed_child} = 1;
    };
```

On my system, `vte_feed_child` should be `0` but if I remove the line `1;`, it selects `1` for `vte_feed_child` and I'm having all kinds of little glitches...

**Comment by syco** [comment]
Yes, if I remove the print statement it changes behaviour.
I've added a second commit for it.

**Pull request merged**
