### PR TITLE
Gtk3 Favourites, Cluster Manager

### PR DESCRIPTION
**Pull request by hanspr**
Fix to issue #245 

Small layout improvement to Cluster Management #180

Plus several fixes to handle terminal or group names with &<>"' characters in it : favourites, confirmation boxes, history

### CODE REVIEW

**Comment by hanspr** [comment]
Added fix to issue #133

It recovers the extra space after collapsing a column

**Comment by hanspr** [comment]
added fix issue #132 

Added subroutine to clean characters before close, the END block does not work. More regex to clean left overs.

**Comment by hanspr** [comment]
fix issue #169

**Comment by hanspr** [comment]
Would you like me to stop or slow down?

I have a fix to #168 

And during the revision of this one, I caught a bug on paste, would not paste multiple nodes with the mouse, only with keys.

And added a small enhancement to show plural legends when there is a single node to copy,cut,paste or multiple nodes.

**Comment by gfrenoy** [comment]
Slow down !?! Certainly not !!  Great that you can find solutions for all those past issues :+1: 

Where I'm a bit confused is that everything is in one huge list of commits ... It would be easier to ingest if there is one PR per topic.  One PR can contain several commits but all related to the same issue.

Maybe this can help : https://datasift.github.io/gitflow/GitFlowForGitHub.html ?

**Comment by gfrenoy** [comment]
Hans,

I believe I merged all your changes ; only re-arranging them by topics and having a more comprehensive commit label (see https://juffalow.com/other/write-good-git-commit-message or https://github.com/ovh-ux/ovh-ux-guidelines/blob/master/.github/CONTRIBUTING.md#git-commit-messages for inspiration about this)

image

Let me know if I forgot anything.

I'll now apply a few more changes.  I guess you'll need to merge this back, create a feature branch from there and then submit the PR.

In any case, thanks again for your help, we're making huge progress, this is great.

**Comment by hanspr** [comment]
Your references are always to git flow, but I do not see a gitflow structure in your repository. So is only as a reference but you do not actually use gitflow I presume.

The other comment in your reference is this:

    Don’t fork repos on GitHub - clone the master repo directly

Should I stop using the fork and clone directly asbru main project?

But can I push a new branch to your project? I'm under the idea that without permissions is necessary to work on a fork to be able to upload changes to a branch, I'm wrong here?

The long story.

The problem is that every time I create a PR, any new changes I publish add up to the one I have already open, I do not know how to create a new PR, after I had opened the first one.

I do have a local features branch but is not on github, and I do commits for single changes so all changes are in different commits, but still every time I create a PR subsecuent commits add to the same one.

What I do is

git ...

* go to github: PR from asbru/gtk3 --> hanspr/gtk3
* pull origin gtk3
* merge
* checkout feature
* git merge gtk3
  * change code
* commit
* checkout gtk3
* go to github: PR from asbru --> hanspr
* pull origin gtk3
* merge
* merge feature
* push origin gtk3
* create PR from hanspr/gtk3 ---> asbru/gtk3
* And repeat this cycle again for the next change

I will read again the new reference you sent me and see If I can work this better.

**Comment by KlaasT** [comment]
How I am doing it. In this case I would branch of gtk3 and work inside my new branch. When I am ready I create a pull request to merge this branch to the upstream gtk3 branch in this case.

When everything is merged and I don't need the feature branche on my fork I just delete it inside my fork to clean up.

For the next type of work I branch of again from gtk3.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by gfrenoy** [comment]
GitFlow is indeed a bit overkill ... Klaas' "shortcut" looks better to me :)

**Comment by hanspr** [comment]
Ok, think I get it, what I need to do is create new branches for every change so each PR comes from different branches; so github is forced to create a new PR

Because I always use the same branch gtk3, every new commit accumulates to the one that is already open.

**Comment by KlaasT** [comment]
Yes it is a bit tedious and you get quite a big collection of branches inside your fork. At least you are able to delete branches again :-)

git branch -d fix-for-1234

**Comment by KlaasT** [comment]
One additional question. Did you by any chance rebase your fork to the origin HEAD? For example (this is an example for master):

> git remote add upstream https://github.com/asbru-cm/asbru-cm.git
> git fetch upstream
> git checkout master
> git reset --hard upstream/master  
> git push origin master --force 
> 

Be aware if you do that now you would lose your local changes.

**Comment by hanspr** [comment]
I've never used those commands I always use the github panel, besides my last PR, I have no further changes, so I guess I could run it after the last PR is accepted. Research what all that means, and how to use it from here on.

**Comment by KlaasT** [comment]
Basically it would fetch all changes from upstream (the official repository) and sets your fork to the state of that upstream repository.

**Pull request closed without merging**
