### PR TITLE
Fix65

### PR DESCRIPTION
**Pull request by hanspr**
## Support for KeePassXC #65 , #343 

The functionality was complete rewriten to address several requests related in the same 2 issues:

* Password no longer required in configuration
    * If password is not provided, will ask for password on load and retain in memory until asbru exits.
* User names and passwords are retrieved from database on the fly at the moment of connection
    * You can change your passwords in keepassxc and in the next connection the new one will be used
    * No passwords are retained in memory or files any more
    * User name and passwords are references now
* Previous implementations would extract absolutely all passwords even when they were not related to any connection, pulling out any other information that a user could have stored like : bank accounts, nips, etc.
    * The full password list was located in memory in a log submenu.
* Button in Connection edit, allows to search entries and doubleclick to select desired entry. The correct format will be inserted in the corresponding fields for user,password or user key and passphrase. Depending on the selected authentication option

imagen

__Search__

* You must type 3 characters or more to start a search

imagen

* During the configuration the application will detect : Version available and capabilities detected on that current version.

imagen

## Limitations found during integration:

* The original proposal was to use <field:uuid>, keepassxc does not allow to retreive the uuid, and last version of keepassxc-cli, no longer allow to search by uuid, so I had to drop it because is not reliable.
* Make sure all titles in keepassxc are different to be able to associate to a unique key

### CODE REVIEW

**Comment by hanspr** [comment]
This should address #56 as well, not tested yet.

**Comment by hanspr** [comment]
@gfrenoy 

Hi Gaëtan, I know we chat about to create a script to migrate current user configurations for keepassxc integration, but I checked the way the tags are created and is impossible, will be a very flawed migration.

The users will have to reassign the entries, but the effort will pay.

**Comment by gfrenoy** [comment]
I don't use this feature so this is not an issue for me but for those who have a long list of entries ; that will be quite a pain !

How can we evaluate who is really using that feature ?  How many entries they have ?  How long would it take take to reconfigure each entry ?

To make it short: what would be the impact ?

**Comment by hanspr** [comment]
Let me rethink the script, I said that I could not automate it (meaning fully automate it), but it does not mean that it could not be an interactive script.

Meaning that I could run over the file and look for the matched entries in the database, and if I find more than 2, then I ask the user to choose the correct key, similar to what the current implementation does in asbru, when it finds more than 1 matches it asks you to select the correct one. For that I would have to use the current KeePass.pm library.

Does it makes sense?

**Comment by gfrenoy** [comment]
Yes, even if it's not fully automated, if there's a way to migrate that we document and explain, it means that the impact will be - hopefully - limited.

But in any case, it's not a change that we should "widely" push without making additional tests and prepare users' questions (in wiki pages or something).

I really think we need to finalize milestone 6.1 (https://github.com/asbru-cm/asbru-cm/milestone/2) and then see what we include in the next release.

**Pull request closed without merging**
