### PR TITLE
Fix556 keybindings

### PR DESCRIPTION
**Pull request by hanspr**
Fix for : #556 #285 #43 #590 #543

__Note: This PR is build on top of restyle-modal-windows__

Added support to customize keybind actions.

Preferences

imagen

Select a row, type your key combination to add to the selected row. `Delete` or `Backspace` disables the corresponding row.

On terminal or Connections list, popup has a show keybindings to list current active keybindings

imagen

imagen

In the Global and Terminal : Remote and Local commands, can have a keybind assigned by placing the cursor on the keybinding field and typing the keybinding.

imagen

Added some additional actions that were not available before. If there are any new actions that should be supported by default, we should add them now.

* Open SFTP connection in SSH terminals `AltCtrl+s`

More actions can be added in the future, but will be less efficient.

### CODE REVIEW

**Comment by gfrenoy** [comment]
Brilliant !!!  Thanks a lot, it was a long time waited feature :)

Do I get it right and some of the "legacy" keybindings have changed ?

As an example, I was using:
- Ctrl+F4 to close current terminal, it is now Ctrl+w
- Ctrl+Shift+V to paste selection, it is now Shift+Insert

Is this on purpose ?

**Comment by hanspr** [comment]
Those were duplicated in the original code (so those actions always had 2 keybindigs associated to it), and under this model you can not have 2 different keybinds for the same action, so I had to sacrifice one of them.

I thought those were the more widely used. I have used `Shift + Insert` since I began using my first terminal 30 years ago.

But change it to anything you like, everything can be rebind now, so it makes no difference to me.

**Comment by gfrenoy** [comment]
> I had to sacrifice one of them

Ok fair enough !  I never noticed there were several bindings for the same thing :)  Thanks for heads up.

So this explains ```Shift + Insert``` but ```Ctrl+w``` is not working on 6.2 ; do I get it right ?

> But change it to anything you like, everything can be rebind now, so it makes no difference to me.

Yes it works great and just takes a few seconds, thanks a million !

I was just wondering if we should pay extra attention to keep the exact same keybindings (by default) or if we should "force" a new default keybindings set and assume users will handle it...?

**Comment by hanspr** [comment]
I don't remember how did I came to `Ctrl+w`

> if we should "force" a new default keybindings

That was not the intention, I was never familiar with the original keybindings because I always disabled them. I think I tried to respect what it was on the code (as I read it). But I can not guaranty that I did not make a mistake.

This is the time to fix any mistake; if I made a boo boo

Feel free to set them up how ever you think is best.

What I really would like to re think; is if there are any useful keybindings that do not exists and could be implemented now.

For example, I was not aware that if you right clicked on an ssh terminal there was a menu entry to open an SFTP session using the settings from that same opened terminal. So I added a new keybinding that was not there before. And since then I have used it several times.

I'm sure there could be more little jewels hidden there that I was not aware of and could be added at this time.

**Comment by hanspr** [comment]
Ok, `Ctrl+w` `Ctrl+F4`

The problem with this ones is that I might misunderstand them.

imagen

imagen

`Ctrl+F4` Closes a Tab
`Ctlr+w` Closes a terminal

By code you can read that both do exaclty the same, but are caught at a different level.

So again, I sacrificed the one from the Tabs, thinking that executing it in the terminal should be enough (and it is).

Reimplementing the first one would be the solution. Adding the action to close a "Tab" that it actually means: close the terminal in the "Tab"

**Comment by hanspr** [comment]
Added the commit to recover the duplicated keybinding to `Ctrl+F4`

At least from a users point of view might look differently thinking about closing a "tab" rather than a terminal.

You will have to reset the defaults, to see the change. I did not want to implement a scanning off all the keybindings to detect new ones. Rather when we close the final version, we add them with a different method when needed.

So, right now during testing is: reset to defaults, test, reset to defaults, etc.

**Comment by gfrenoy** [comment]
> ```Ctrl+F4``` Closes a Tab
> ```Ctrl+w```  Closes a terminal
> By code you can read that both do exaclty the same, but are caught at a different level.

Indeed, I see ; thanks for pointing that out !

But ```Ctrl+w``` did not work in the past versions and now they both have the exact same behavior ; I'd like to review this.

I believe they should match the "Disconnect" and "Close Terminal" options we had:

image

Said differently : ```Ctrl+w``` should not close the tab.

Another annoying regression I noticed is that it does not reconnect when you hit "ENTER":

image

Let me do a few more tests as you suggested and see what I can do to smooth the upgrade process.

Thanks again !

**Comment by hanspr** [comment]
>  I noticed is that it does not reconnect when you hit "ENTER"

Missed that one, thanks.

**Comment by gfrenoy** [comment]
Don't know if you noticed but this actually also nicely fixes also #543 :)

**Comment by hanspr** [comment]
> Don't know if you noticed but this actually also nicely fixes also #543 :)

Yes I did know

**Pull request merged**
